### ISSUE TITLE
Death and inflicting damage

### ISSUE THREAD

**Issue by lare96** [luna-rs/luna#142]

**Comment by notjuanortiz** [comment]
I've compiled this list just so that there's a clear feature set for death.
## Player
- [ ] losing all but X amount of items (default), removing all items from equipment.
- [ ] losing all items (i.e dying while skulled), removing all items from equipment.
- [ ] not losing any items (i.e dying while playing castle wars)
- [ ] Re-spawn location based on current spell-book ( blocked by #102 )

## Non-player character
- [ ] Randomized item drop for killer(s) from database
- [ ] Configurable re-spawn timer based on combat-level 

## Both
- [ ] Attacker(s)'s current target reset
- [ ] Victim's current target reset
- [ ] Victim's health/stats reset
